### ISSUE TITLE
[FEATURE] New GitHub stats display

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/PortfolioFy#11]
Currently, there are 2 choices for stats display. I want more interactive stats to be made available to the community. Search the internet, and include them in currently available levels.

**Comment by sj056** [comment]
@kaustubhgupta hey! can I add most used languages stats card?

**Comment by kaustubhgupta** [comment]
umm no, I am looking for whole GitHub stats like this https://github.com/anuraghazra/github-readme-stats and this https://github.com/lowlighter/metrics

**Comment by kaustubhgupta** [comment]
@sj056 did you found any full stats with respect to this?

**Comment by kaustubhgupta** [comment]
Issue to be continued in #36
