### ISSUE TITLE
[README] Add contributors Updation Method

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/PortfolioFy#12]
Come up with a solution to integrate the contributors display in the readme file after the "Special Mentions" section. The section should update the contributor's list as soon as any new contributor make commits to the repo. Either a GitHub bot can be integrated or anything interesting you would like to discuss.

**Comment by shikharcodes** [comment]
Hey @kaustubhgupta , I would like to add this feature by using a link to the insights section of this project. Can you please assign this issue to me under SWoC?

**Comment by kaustubhgupta** [comment]
Can you share some screenshots/links where you found this implementation. I would like to see how it looks

**Comment by kaustubhgupta** [comment]
@shikharcodes Are you working on the suggested changes? Let me know if you face any issues!

**Comment by shikharcodes** [comment]
yes I'm working on it, but if I'm using attributes inside img tag here, the dimensions of user's profile images are being impacted negatively. Is there any other way which you can suggest to increase the size of the user's profile images?

**Comment by kaustubhgupta** [comment]
Oh, that's the issue, nevermind, I will manage this size. This PR will be merged soon. You can look at other issues if you wish to contribute more to this project!

**Comment by kaustubhgupta** [comment]
Just update the PR with heading level issue

**Comment by shikharcodes** [comment]
Yeah sure, thanks!

**Comment by shikharcodes** [comment]
I've done the requested change, please review and merge @kaustubhgupta
