### ISSUE TITLE
[DOCS] Shifting from Wikis to GitHub pages

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/PortfolioFy#14]
Currently, the documentation of the project is available on Wikis. Now I want to host it as independent pages on GitHub. Figure out a way to do this. I want to know your ideas first and then I will discuss mine.

**Comment by raman08** [comment]
We can parse the markdown to display it in the website

**Comment by kaustubhgupta** [comment]
Do you want to work on this issue? Also are you proposing GitHub pages for this documentation?

**Comment by raman08** [comment]
Yes sir, I was thinking to build it on GitHub pages as it will be easy to deploy and manage.
Also any changes in documents will automatically be reflected in the site

**Comment by kaustubhgupta** [comment]
Okay, I am assigning this issue to you. Make a PR and then I will suggest if any changes are required or not

**Comment by raman08** [comment]
Sir, I was thinking to make make the wikis through the docsify service.

**Comment by kaustubhgupta** [comment]
Go to the wikis page, then on the right panel, you will get the clone link:
`https://github.com/kaustubhgupta/PortfolioFy.wiki.git`

Clone it and you will get all the required markdown files. 

I saw this service. Could you tell me how we will update the new features of the project in this? I didn't get the idea about that

**Comment by raman08** [comment]
Sir, I was planning to make a Default wiki directory, where all of the markdown files will be placed and then we will add it to the docsfiy service. So any change in the readme will directly be reflected in the Github pages.

**Comment by raman08** [comment]
This service will automatically change the written markdown file into equivalent HTML and CSS snippet. So when someone changes the wiki it will automatically be reflected in the github pages

**Comment by raman08** [comment]
Hello, Sir, there is a problem. I need all the wiki files in the docs folder in the main code for this to work. I had done some research on it and I found the two ways to do it

1. Either you add a remote to the wiki page and whenever you update the wiki page you can push the changes to the main code through that remote.
2. The other way is to add git submodules (this is more difficult than the other one).

Sir, Kindly let me know whats you thought about the same.
For reference, you can go to [this](https://stackoverflow.com/questions/6941688/how-to-integrate-a-github-wiki-into-the-main-project?rq=1)

**Comment by kaustubhgupta** [comment]
Create a docs folder in the root directory of the project and put all the wikis in that.

**Comment by kaustubhgupta** [comment]
Are you able to proceed with this service or you are stuck anywhere?

**Comment by raman08** [comment]
@kaustubhgupta Sir, Any Update or recomendation
