### ISSUE TITLE
[DOCS] Adding a Code of Conduct file

### ISSUE THREAD

**Issue by shikharcodes** [kaustubhgupta/PortfolioFy#17]
Hey @kaustubhgupta , while looking at this project I noticed that the Code of Conduct file is missing.
I would like to add this if you want. Please assign me this under Swoc label.

**Comment by kaustubhgupta** [comment]
assigned to you

**Comment by shikharcodes** [comment]
Can you also share the contact email that I would mention in the file?
Also, should it address to maintainers or maintainer, i.e. you maintain the project alone or there are others too because then I'll use grammar in that way?

**Comment by kaustubhgupta** [comment]
Currently, there is no other maintainer for this project. Instead of email id, redirect them to LinkedIn. 
https://www.linkedin.com/in/kaustubh-gupta

**Comment by shikharcodes** [comment]
I've added the file @kaustubhgupta. Please review and merge.

**Comment by shikharcodes** [comment]
Hey @kaustubhgupta, just wanted to know that have you sent the project's stats to the SWoC team so that our points can be synced on the SWoC leaderboard?

**Comment by kaustubhgupta** [comment]
Yes, the scores have been shared with the team on 3rd Feb

**Comment by shikharcodes** [comment]
> Yes, the scores have been shared with the team on 3rd Feb

Okay, thank you :)
