### ISSUE TITLE
Add Issue Template and Pull Request template

### ISSUE THREAD

**Issue by deytulsi18** [kaustubhgupta/PortfolioFy#20]
Can I add Issue Template and Pull Request template suitable for this project?

**Comment by kaustubhgupta** [comment]
Hi @deytulsi18! Are you a participant of SWOC or you are contributing casually?

**Comment by deytulsi18** [comment]
Yes I am participating in SWoC but I am new to open source so I choose this easy task.

**Comment by kaustubhgupta** [comment]
@deytulsi18 Okay, I have assigned it to you. Raise a PR with your understanding and I will assist if any changes are needed!
