### ISSUE TITLE
[FEATURE] Add more social links to level 2

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/PortfolioFy#8]
Currently, the webpage has GitHub Profile Link. According to the user's feedback, more social links should be added. Currently, these links are to be supported:
- Linkedin
- Medium
- Facebook
- Twitter

If you want to add more handles then kindly discuss. Also, whosoever takes this issue first discuss your approach for this. I have an approach but I want you to brainstorm first.

**Comment by Jatin-MaTTriX** [comment]
can i work on this ? I will add some more social links on the right of it in a line  ? it is ok?

**Comment by kaustubhgupta** [comment]
@Jatin-MaTTriX you need to update the level 2 HTML code plus take inputs from the user about the links. I would suggest taking them as a dictionary with a key as a handle name and value as a URL. Try this in the local terminal if this works I will guide you about how to update them in the action.yml file.

**Comment by Jatin-MaTTriX** [comment]
@kaustubhgupta  sir i am not able to find the correct html file for level 2 theme and file with .py extension is new for me . As I am a newbie i only know about (.html file , css , js , bootstrap) i don't kmow about python . can you help me out what should i do ?.

**Comment by kaustubhgupta** [comment]
The HTML file is not present as it is in the project and needs to be generated locally: https://github.com/kaustubhgupta/PortfolioFy/wiki/Setting-Up-Locally

If you are unaware of Python then I will help you set up the dataflow for this.

**Comment by Jatin-MaTTriX** [comment]
OK Sir I Will set it up locally

**Comment by kaustubhgupta** [comment]
@Jatin-MaTTriX Are you working on this? Let me know if you face any issues!

**Comment by Jatin-MaTTriX** [comment]
I am currently out of station. I will resume my work after 3 days. Srry sir
for inconvenience

**Comment by kaustubhgupta** [comment]
No issues!

**Comment by Jatin-MaTTriX** [comment]
sir I am not able to set it up locally .

**Comment by kaustubhgupta** [comment]
@Jatin-MaTTriX what issues you are facing?

**Comment by Jatin-MaTTriX** [comment]
pip install -r requirements.txt   Sir this command is not working

**Comment by Jatin-MaTTriX** [comment]
"requirement.txt file not present in module " this error is shown

**Comment by kaustubhgupta** [comment]
You need to run this command while being in the project folder. Run this command by opening the terminal in the project folder

**Comment by Jatin-MaTTriX** [comment]
I have already done this..but nothing happened

**Comment by kaustubhgupta** [comment]
I am not sure why it's not working on your side, are you have installed python?

**Comment by Jatin-MaTTriX** [comment]
Yes I have installed it

**Comment by Jatin-MaTTriX** [comment]
I will do something for it.. Give me some time

**Comment by kaustubhgupta** [comment]
okay then do this:
```bash 
pip install PyGithub
```

**Comment by kaustubhgupta** [comment]
@Jatin-MaTTriX updates?

**Comment by Jatin-MaTTriX** [comment]
Still not working sir

**Comment by Jatin-MaTTriX** [comment]
![ssss](https://user-images.githubusercontent.com/72266203/105320319-089f5000-5bec-11eb-8f3c-3b2b14b55324.PNG)

Sir like this i have to add icon ? this is just sample

**Comment by Jatin-MaTTriX** [comment]
@kaustubhgupta  Sir this is acceptable ?

**Comment by kaustubhgupta** [comment]
you are talking about the second GitHub icon,?

**Comment by Jatin-MaTTriX** [comment]
yes like 2nd github

**Comment by kaustubhgupta** [comment]
> Still not working sir

Did you install the Python correctly?  Are you able to run the Python programs?

**Comment by kaustubhgupta** [comment]
> yes like 2nd github

Okay, then you can add the social icons of the handles mentioned in the issue description

**Comment by Jatin-MaTTriX** [comment]
> > Still not working sir
> 
> Did you install the Python correctly? Are you able to run the Python programs?  
no sir python is not installed

**Comment by Jatin-MaTTriX** [comment]
> > yes like 2nd github
> 
> Okay, then you can add the social icons of the handles mentioned in the issue description

ok

**Comment by kaustubhgupta** [comment]
> Yes I have installed it

> > > Still not working sir
> > 
> > 
> > Did you install the Python correctly? Are you able to run the Python programs?

no sir python is not installed

You said 3 days earlier that Python is installed?

**Comment by Jatin-MaTTriX** [comment]
i don't know how to use python .i have installed it earlier but i have not used it

**Comment by Jatin-MaTTriX** [comment]
i only edit html file

**Comment by Jatin-MaTTriX** [comment]
by observing code i found html file 
so i started editing in it

**Comment by kaustubhgupta** [comment]
umm, that would create issues for me to manage the logics for the same,

**Comment by kaustubhgupta** [comment]
I think you should switch to another issue as this would require both python and HTML knowledge

**Comment by Jatin-MaTTriX** [comment]
Sure Sir

**Comment by kaustubhgupta** [comment]
Commit https://github.com/kaustubhgupta/PortfolioFy/commit/3e4b1bb98fc719ae4c96860a9c29ebb6a15d9cc2 solved this issue
