### ISSUE TITLE
[FEATURE] Latest Tweets Display

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/PortfolioFy#9]
For all the levels, we want to integrate them and put out the last 3 tweets of the user. The Twitter username can be obtained from the user. We don't want the user to pass their Twitter Authentication token and figure out the mechanism to obtain the tweets with any 3rd-party library or web scrapping.

**Comment by sammy8825** [comment]
I would like to work on this issue @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@sammy8825 Assigned to you. Let me know if you clearly understood the situation and need any help!

**Comment by sammy8825** [comment]
For now I understood the issue. Is there any other way to communicate?

**Comment by kaustubhgupta** [comment]
Slack or this issues comments. I am most active on Github. If you wish, you can create separate discussions for this.

**Comment by sammy8825** [comment]
Ok 👍

**Comment by kaustubhgupta** [comment]
@sammy8825 updates?

**Comment by sammy8825** [comment]
Searching the methods sir

**Comment by sammy8825** [comment]
I ain't feeling well sir u can assign it to someone else

**Comment by kaustubhgupta** [comment]
To be continued in issue #37
